---
version: '3.8'
name: intranet-trece

services:
  traefik:
    image: traefik:v2.10

    ports:
      - 80:80

    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.intranet-trece.localhost`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.service=api@internal
      - traefik.http.services.traefik-public.loadbalancer.server.port=8000

      # GENERIC MIDDLEWARES
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
  
  frontend:
    image: ghcr.io/ronyerisson/intranet-trece-frontend:latest

  backend:
    image: ghcr.io/ronyerisson/intranet-trece-backend:latest

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: LPruALWQRXpR
      POSTGRES_DB: plone
    volumes:
      - vol-site-data:/var/lib/postgresql/data

volumes:
  vol-site-data: {}
